// ~130 questions FR pour "Qui ?"
// Chaque question porte une tonalité qui colore l'UI et alimente le bulletin final :
//   "warm"  → le meilleur de chacun (compliment, on célèbre)   ✨
//   "spicy" → le pire de chacun (clash, gênant, on chambre)    🔥
//   "fun"   → neutre / absurde / prédiction (juste pour rire)  😏

export const QUESTIONS = [
  // ─── WARM — le meilleur de chacun ───
  { text: "Qui est la personne la plus gentille du groupe ?", tone: "warm" },
  { text: "Qui ferait n'importe quoi pour ses amis ?", tone: "warm" },
  { text: "Qui a le plus grand cœur ?", tone: "warm" },
  { text: "Qui est le plus loyal en amitié ?", tone: "warm" },
  { text: "Qui te ferait rire même dans tes pires jours ?", tone: "warm" },
  { text: "Qui appellerais-tu à 3h du matin en cas de crise ?", tone: "warm" },
  { text: "Qui fait les meilleurs câlins du groupe ?", tone: "warm" },
  { text: "Qui ferait le meilleur parent ?", tone: "warm" },
  { text: "Qui mérite plus qu'il n'a déjà ?", tone: "warm" },
  { text: "Qui te manquerait le plus pendant un an de voyage seul ?", tone: "warm" },
  { text: "Qui rend tout le monde de bonne humeur en arrivant ?", tone: "warm" },
  { text: "Qui sait toujours quoi dire quand ça va mal ?", tone: "warm" },
  { text: "Qui est le plus authentique du groupe ?", tone: "warm" },
  { text: "Qui porte le plus lourd sans jamais se plaindre ?", tone: "warm" },
  { text: "Qui semble avoir tout compris à la vie ?", tone: "warm" },
  { text: "Qui est le plus en paix avec lui-même ?", tone: "warm" },
  { text: "Qui sera le plus regretté le jour où il partira ?", tone: "warm" },
  { text: "Qui est la maman du groupe ?", tone: "warm" },
  { text: "Qui est le papa du groupe ?", tone: "warm" },
  { text: "Qui organise toujours tout ?", tone: "warm" },
  { text: "Qui ramène la meilleure énergie en soirée ?", tone: "warm" },
  { text: "Qui calme le jeu quand ça part en vrille ?", tone: "warm" },
  { text: "Qui ferait le meilleur thérapeute ?", tone: "warm" },
  { text: "Qui ferait le meilleur prof ?", tone: "warm" },
  { text: "Qui ferait le meilleur président ?", tone: "warm" },
  { text: "Qui aura le job le plus impressionnant ?", tone: "warm" },
  { text: "Qui ne vieillira jamais vraiment dans sa tête ?", tone: "warm" },

  // ─── SPICY — le pire de chacun ───
  { text: "Qui est le plus toxique en couple ?", tone: "spicy" },
  { text: "Qui ment le plus souvent ?", tone: "spicy" },
  { text: "Qui ne pourrait pas garder un secret 24h ?", tone: "spicy" },
  { text: "Qui te trahirait pour un million d'euros ?", tone: "spicy" },
  { text: "Qui est le plus jaloux secrètement ?", tone: "spicy" },
  { text: "Qui parle le plus dans le dos des autres ?", tone: "spicy" },
  { text: "Qui est le plus égoïste sans s'en rendre compte ?", tone: "spicy" },
  { text: "Qui changerait totalement s'il devenait riche ?", tone: "spicy" },
  { text: "Qui pense être bien meilleur qu'il ne l'est ?", tone: "spicy" },
  { text: "Qui a l'ego le plus fragile ?", tone: "spicy" },
  { text: "Qui se prend beaucoup trop au sérieux ?", tone: "spicy" },
  { text: "Qui fait le moins d'efforts en relation ?", tone: "spicy" },
  { text: "Qui a déjà ghosté quelqu'un sans pitié ?", tone: "spicy" },
  { text: "Qui regarde son téléphone pendant qu'on lui parle ?", tone: "spicy" },
  { text: "Qui juge les autres en silence ?", tone: "spicy" },
  { text: "Qui craquerait en premier sous la torture ?", tone: "spicy" },
  { text: "Qui est le plus dramatique du groupe ?", tone: "spicy" },
  { text: "Qui annule toujours à la dernière minute ?", tone: "spicy" },
  { text: "Qui arrive systématiquement en retard ?", tone: "spicy" },
  { text: "Qui oublie son portefeuille à chaque sortie ?", tone: "spicy" },
  { text: "Qui stalke le plus ses ex ?", tone: "spicy" },
  { text: "Qui a la galerie photo la plus suspecte ?", tone: "spicy" },
  { text: "Qui a déjà envoyé un message à la mauvaise personne ?", tone: "spicy" },
  { text: "Qui ment sur son nombre de partenaires ?", tone: "spicy" },
  { text: "Qui a la pire playlist secrète ?", tone: "spicy" },
  { text: "Qui sera le premier à divorcer ?", tone: "spicy" },
  { text: "Qui finira seul avec 7 chats ?", tone: "spicy" },
  { text: "Qui sait le mieux mentir en gardant son sang-froid ?", tone: "spicy" },
  { text: "Qui ferait fortune dans l'arnaque ?", tone: "spicy" },
  { text: "Qui rejoindrait une secte sans s'en rendre compte ?", tone: "spicy" },

  // ─── FUN — neutre, absurde, prédictions ───
  { text: "Qui rit le plus à ses propres blagues ?", tone: "fun" },
  { text: "Qui ferait le pire DJ de mariage ?", tone: "fun" },
  { text: "Qui chante le plus faux sous la douche ?", tone: "fun" },
  { text: "Qui parle le plus pendant un film ?", tone: "fun" },
  { text: "Qui pose les questions les plus bizarres ?", tone: "fun" },
  { text: "Qui passerait 3h à se prendre en photo ?", tone: "fun" },
  { text: "Qui se perd dans son propre quartier ?", tone: "fun" },
  { text: "Qui prend les pires décisions en soirée ?", tone: "fun" },
  { text: "Qui raconte la même histoire pour la 100ème fois ?", tone: "fun" },
  { text: "Qui parle à son chien comme à un humain ?", tone: "fun" },
  { text: "Qui danse le plus mal mais le plus fort ?", tone: "fun" },
  { text: "Qui crie le plus dans une fête foraine ?", tone: "fun" },
  { text: "Qui rate son réveil chaque matin ?", tone: "fun" },
  { text: "Qui ferait le pire imitateur de Macron ?", tone: "fun" },
  { text: "Qui parle tout seul quand personne ne regarde ?", tone: "fun" },
  { text: "Qui a déjà fait semblant de connaître une chanson ?", tone: "fun" },
  { text: "Qui chante du Céline Dion en cachette ?", tone: "fun" },
  { text: "Qui aurait survécu à une autre époque ?", tone: "fun" },
  { text: "Qui pense à la mort un peu trop souvent ?", tone: "fun" },
  { text: "Qui vit comme si demain n'existait pas ?", tone: "fun" },
  { text: "Qui a le plus changé ces dernières années ?", tone: "fun" },
  { text: "Qui cache le mieux ses vraies émotions ?", tone: "fun" },
  { text: "Qui sera le plus riche dans 10 ans ?", tone: "fun" },
  { text: "Qui se mariera en premier ?", tone: "fun" },
  { text: "Qui aura le plus d'enfants ?", tone: "fun" },
  { text: "Qui vivra à l'étranger ?", tone: "fun" },
  { text: "Qui deviendra célèbre ?", tone: "fun" },
  { text: "Qui aura la plus belle maison ?", tone: "fun" },
  { text: "Qui changera complètement de vie à 40 ans ?", tone: "fun" },
  { text: "Qui survivrait sur une île déserte ?", tone: "fun" },
  { text: "Qui serait le meilleur dans Koh-Lanta ?", tone: "fun" },
  { text: "Qui s'en sortirait avec 50€ pour un mois ?", tone: "fun" },
  { text: "Qui ferait le meilleur cuisinier de restaurant étoilé ?", tone: "fun" },
  { text: "Qui survivrait à une apocalypse zombie ?", tone: "fun" },
  { text: "Qui serait l'imposteur dans Among Us ?", tone: "fun" },
  { text: "Qui se ferait éliminer en premier dans Squid Game ?", tone: "fun" },
  { text: "Qui mangerait un insecte pour 100€ ?", tone: "fun" },
  { text: "Qui appellerait sa mère en premier en cas de problème ?", tone: "fun" },
  { text: "Qui monterait une secte qui marche vraiment ?", tone: "fun" },
  { text: "Qui ferait le meilleur cambrioleur ?", tone: "fun" },
  { text: "Qui gagnerait une bagarre de bar ?", tone: "fun" },
  { text: "Qui irait combattre un ours pour de l'argent ?", tone: "fun" },
  { text: "Qui ferait le pire candidat de télé-réalité ?", tone: "fun" },
  { text: "Qui paniquerait en premier dans un avion qui tremble ?", tone: "fun" },
  { text: "Qui parlerait à un fantôme par pure curiosité ?", tone: "fun" },
  { text: "Qui vendrait un rein pour partir en vacances ?", tone: "fun" },
  { text: "Qui paye toujours sa part au centime près ?", tone: "fun" },
  { text: "Qui gagnerait un quiz de culture générale ?", tone: "fun" },
];

// Mélange Fisher-Yates et pioche N questions sans doublon
export function pickQuestions(count) {
  const arr = [...QUESTIONS];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, Math.min(count, arr.length));
}
