// Banque de questions de départ (seed).
// Chaque question porte une CLÉ de catégorie (cat). La catégorie définit
// l'ambiance/couleur en jeu (warm / spicy / fun) — voir DEFAULT_CATEGORIES
// dans store.js. L'admin peut ensuite tout réorganiser librement.

export const QUESTIONS = [
  // ─── 💛 Gentillesse (warm) ───
  { text: "Qui est la personne la plus gentille du groupe ?", cat: "gentil" },
  { text: "Qui ferait n'importe quoi pour ses amis ?", cat: "gentil" },
  { text: "Qui a le plus grand cœur ?", cat: "gentil" },
  { text: "Qui est le plus loyal en amitié ?", cat: "gentil" },
  { text: "Qui te ferait rire même dans tes pires jours ?", cat: "gentil" },
  { text: "Qui appellerais-tu à 3h du matin en cas de crise ?", cat: "gentil" },
  { text: "Qui fait les meilleurs câlins du groupe ?", cat: "gentil" },
  { text: "Qui ferait le meilleur parent ?", cat: "gentil" },
  { text: "Qui mérite plus qu'il n'a déjà ?", cat: "gentil" },
  { text: "Qui te manquerait le plus pendant un an de voyage seul ?", cat: "gentil" },
  { text: "Qui sait toujours quoi dire quand ça va mal ?", cat: "gentil" },
  { text: "Qui est le plus authentique du groupe ?", cat: "gentil" },
  { text: "Qui porte le plus lourd sans jamais se plaindre ?", cat: "gentil" },
  { text: "Qui adopterait le chien que personne ne veut ?", cat: "gentil" },
  { text: "Qui rendrait visite à un ami à l'hôpital sans qu'on lui demande ?", cat: "gentil" },
  { text: "Qui partagerait son dernier carré de chocolat sans hésiter ?", cat: "gentil" },
  { text: "Qui se souvient toujours de ton anniversaire ?", cat: "gentil" },
  { text: "Qui pardonne le plus facilement ?", cat: "gentil" },
  { text: "Qui défendrait un inconnu qui se fait embêter dans la rue ?", cat: "gentil" },
  { text: "Qui laisse sa place dans le métro sans réfléchir ?", cat: "gentil" },
  { text: "Qui écoute vraiment quand tu parles ?", cat: "gentil" },
  { text: "Qui t'envoie un message juste pour prendre des nouvelles ?", cat: "gentil" },
  { text: "Qui ferait un détour de deux heures pour rendre service ?", cat: "gentil" },
  { text: "Qui consolerait un parfait inconnu en larmes ?", cat: "gentil" },
  { text: "Qui donne sans jamais rien attendre en retour ?", cat: "gentil" },
  { text: "Qui se réjouit le plus sincèrement du bonheur des autres ?", cat: "gentil" },
  { text: "Qui n'a jamais vraiment dit du mal de personne ?", cat: "gentil" },
  { text: "Qui prendrait soin de toi si tu étais malade ?", cat: "gentil" },
  { text: "Qui héberge ceux qui n'ont nulle part où dormir ?", cat: "gentil" },
  { text: "Qui pense aux autres avant de penser à lui ?", cat: "gentil" },
  { text: "Qui mérite une médaille de la patience ?", cat: "gentil" },
  { text: "Qui croit en toi même quand tu n'y crois plus ?", cat: "gentil" },
  { text: "Qui rend le monde un peu meilleur juste en étant là ?", cat: "gentil" },
  { text: "Qui dit toujours oui quand on a besoin de lui ?", cat: "gentil" },
  { text: "Qui offre les cadeaux les plus attentionnés ?", cat: "gentil" },

  // ─── 🦸 Talents (warm) ───
  { text: "Qui ferait le meilleur thérapeute ?", cat: "talents" },
  { text: "Qui ferait le meilleur prof ?", cat: "talents" },
  { text: "Qui ferait le meilleur président ?", cat: "talents" },
  { text: "Qui s'en sortirait avec 50€ pour un mois ?", cat: "talents" },
  { text: "Qui ferait le meilleur cuisinier de restaurant étoilé ?", cat: "talents" },
  { text: "Qui gagnerait un quiz de culture générale ?", cat: "talents" },
  { text: "Qui ferait le meilleur avocat ?", cat: "talents" },
  { text: "Qui ferait le meilleur médecin urgentiste ?", cat: "talents" },
  { text: "Qui réussirait le mieux en montant sa propre boîte ?", cat: "talents" },
  { text: "Qui improviserait le meilleur discours sans préparation ?", cat: "talents" },
  { text: "Qui réparerait n'importe quoi avec trois bouts de scotch ?", cat: "talents" },
  { text: "Qui apprendrait une nouvelle langue en un mois ?", cat: "talents" },
  { text: "Qui gérerait le mieux une crise sous pression ?", cat: "talents" },
  { text: "Qui ferait le meilleur capitaine d'équipe ?", cat: "talents" },
  { text: "Qui pourrait faire rire une salle entière sur scène ?", cat: "talents" },
  { text: "Qui ferait le meilleur négociateur d'otages ?", cat: "talents" },
  { text: "Qui survivrait un mois seul en pleine nature ?", cat: "talents" },
  { text: "Qui ferait le meilleur détective ?", cat: "talents" },
  { text: "Qui se débrouille dans absolument n'importe quelle situation ?", cat: "talents" },
  { text: "Qui ferait le meilleur coach sportif ?", cat: "talents" },
  { text: "Qui ferait le meilleur diplomate ?", cat: "talents" },
  { text: "Qui a un talent caché que personne ne soupçonne ?", cat: "talents" },
  { text: "Qui ferait le meilleur pompier ?", cat: "talents" },
  { text: "Qui pourrait devenir influenceur du jour au lendemain ?", cat: "talents" },
  { text: "Qui ferait le meilleur pilote dans une course-poursuite ?", cat: "talents" },
  { text: "Qui pourrait diriger une entreprise de cent personnes ?", cat: "talents" },
  { text: "Qui ferait le meilleur barman qui connaît tout le monde ?", cat: "talents" },
  { text: "Qui apprend le plus vite quand il s'y met vraiment ?", cat: "talents" },
  { text: "Qui ferait le meilleur guide de haute montagne ?", cat: "talents" },
  { text: "Qui ferait le meilleur magicien ?", cat: "talents" },
  { text: "Qui garderait son sang-froid en pleine tempête ?", cat: "talents" },
  { text: "Qui ferait le meilleur enquêteur infiltré ?", cat: "talents" },

  // ─── 👥 Le groupe (warm) ───
  { text: "Qui rend tout le monde de bonne humeur en arrivant ?", cat: "groupe" },
  { text: "Qui est la maman du groupe ?", cat: "groupe" },
  { text: "Qui est le papa du groupe ?", cat: "groupe" },
  { text: "Qui organise toujours tout ?", cat: "groupe" },
  { text: "Qui ramène la meilleure énergie en soirée ?", cat: "groupe" },
  { text: "Qui calme le jeu quand ça part en vrille ?", cat: "groupe" },
  { text: "Qui lance toujours les plans de vacances ?", cat: "groupe" },
  { text: "Qui gère les réservations de resto ?", cat: "groupe" },
  { text: "Qui ramène le plus de nouvelles têtes dans le groupe ?", cat: "groupe" },
  { text: "Qui connaît tous les potins ?", cat: "groupe" },
  { text: "Qui est le ciment du groupe ?", cat: "groupe" },
  { text: "Qui réconcilie tout le monde après une embrouille ?", cat: "groupe" },
  { text: "Qui se lance le premier sur la piste de danse ?", cat: "groupe" },
  { text: "Qui propose toujours « un dernier verre » ?", cat: "groupe" },
  { text: "Qui prend toutes les photos de groupe ?", cat: "groupe" },
  { text: "Qui crée le groupe de discussion pour chaque événement ?", cat: "groupe" },
  { text: "Qui répond toujours en dernier dans la conversation ?", cat: "groupe" },
  { text: "Qui relance quand plus personne ne parle ?", cat: "groupe" },
  { text: "Qui ramène à manger sans qu'on demande ?", cat: "groupe" },
  { text: "Qui est le GPS humain de la bande ?", cat: "groupe" },
  { text: "Qui gère le budget commun en voyage ?", cat: "groupe" },
  { text: "Qui se souvient de toutes les anecdotes du groupe ?", cat: "groupe" },
  { text: "Qui est toujours partant, quel que soit le plan ?", cat: "groupe" },
  { text: "Qui organise les anniversaires surprises ?", cat: "groupe" },
  { text: "Qui irait te chercher à 4h du matin sans râler ?", cat: "groupe" },
  { text: "Qui a toujours un bon plan pour tout ?", cat: "groupe" },
  { text: "Qui manquerait le plus s'il quittait le groupe ?", cat: "groupe" },
  { text: "Qui joue le grand frère ou la grande sœur ?", cat: "groupe" },
  { text: "Qui finit toujours par régler l'addition ?", cat: "groupe" },
  { text: "Qui motive le groupe à sortir un dimanche pluvieux ?", cat: "groupe" },
  { text: "Qui est le plus dur à faire venir à une soirée ?", cat: "groupe" },
  { text: "Qui connaît le mieux chacun du groupe ?", cat: "groupe" },

  // ─── 😂 Drôle (fun) ───
  { text: "Qui rit le plus à ses propres blagues ?", cat: "drole" },
  { text: "Qui ferait le pire DJ de mariage ?", cat: "drole" },
  { text: "Qui chante le plus faux sous la douche ?", cat: "drole" },
  { text: "Qui parle le plus pendant un film ?", cat: "drole" },
  { text: "Qui pose les questions les plus bizarres ?", cat: "drole" },
  { text: "Qui passerait 3h à se prendre en photo ?", cat: "drole" },
  { text: "Qui se perd dans son propre quartier ?", cat: "drole" },
  { text: "Qui prend les pires décisions en soirée ?", cat: "drole" },
  { text: "Qui raconte la même histoire pour la 100ème fois ?", cat: "drole" },
  { text: "Qui parle à son chien comme à un humain ?", cat: "drole" },
  { text: "Qui danse le plus mal mais le plus fort ?", cat: "drole" },
  { text: "Qui crie le plus dans une fête foraine ?", cat: "drole" },
  { text: "Qui rate son réveil chaque matin ?", cat: "drole" },
  { text: "Qui ferait le pire imitateur de Macron ?", cat: "drole" },
  { text: "Qui parle tout seul quand personne ne regarde ?", cat: "drole" },
  { text: "Qui chante du Céline Dion en cachette ?", cat: "drole" },
  { text: "Qui paye toujours sa part au centime près ?", cat: "drole" },
  { text: "Qui a le rire le plus contagieux ?", cat: "drole" },
  { text: "Qui rit au pire moment possible ?", cat: "drole" },
  { text: "Qui fait les meilleures imitations ?", cat: "drole" },
  { text: "Qui raconte une blague que personne ne comprend ?", cat: "drole" },
  { text: "Qui se prend les pieds dans le tapis le plus souvent ?", cat: "drole" },
  { text: "Qui envoie les memes les plus drôles ?", cat: "drole" },
  { text: "Qui s'endort le premier devant un film ?", cat: "drole" },
  { text: "Qui a toujours une histoire improbable à raconter ?", cat: "drole" },
  { text: "Qui rate systématiquement la chute de ses blagues ?", cat: "drole" },
  { text: "Qui parle avec les mains de façon incontrôlable ?", cat: "drole" },
  { text: "Qui confond tout le temps les prénoms des gens ?", cat: "drole" },
  { text: "Qui rigole tout seul en repensant à un truc ?", cat: "drole" },
  { text: "Qui mange comme si c'était son dernier repas ?", cat: "drole" },
  { text: "Qui a le réveil le plus dramatique au monde ?", cat: "drole" },
  { text: "Qui fait les bruitages les plus bizarres ?", cat: "drole" },
  { text: "Qui transforme la moindre galère en fou rire ?", cat: "drole" },

  // ─── 🔮 Prédictions (fun) ───
  { text: "Qui aura le job le plus impressionnant ?", cat: "futur" },
  { text: "Qui ne vieillira jamais vraiment dans sa tête ?", cat: "futur" },
  { text: "Qui sera le plus riche dans 10 ans ?", cat: "futur" },
  { text: "Qui se mariera en premier ?", cat: "futur" },
  { text: "Qui aura le plus d'enfants ?", cat: "futur" },
  { text: "Qui vivra à l'étranger ?", cat: "futur" },
  { text: "Qui deviendra célèbre ?", cat: "futur" },
  { text: "Qui aura la plus belle maison ?", cat: "futur" },
  { text: "Qui changera complètement de vie à 40 ans ?", cat: "futur" },
  { text: "Qui ouvrira un bar sur une plage ?", cat: "futur" },
  { text: "Qui finira maire de son village ?", cat: "futur" },
  { text: "Qui enchaînera les mariages et les divorces ?", cat: "futur" },
  { text: "Qui fera le tour du monde sac au dos ?", cat: "futur" },
  { text: "Qui lâchera tout pour vivre dans un van ?", cat: "futur" },
  { text: "Qui passera à la télé pour une raison improbable ?", cat: "futur" },
  { text: "Qui écrira un livre un jour ?", cat: "futur" },
  { text: "Qui deviendra riche puis perdra tout ?", cat: "futur" },
  { text: "Qui vieillira le mieux ?", cat: "futur" },
  { text: "Qui restera célibataire le plus longtemps ?", cat: "futur" },
  { text: "Qui sera le premier à devenir grand-parent ?", cat: "futur" },
  { text: "Qui se reconvertira dans un métier totalement inattendu ?", cat: "futur" },
  { text: "Qui deviendra complotiste sur le tard ?", cat: "futur" },
  { text: "Qui finira par revenir vivre près de ses parents ?", cat: "futur" },
  { text: "Qui réalisera vraiment son rêve d'enfant ?", cat: "futur" },
  { text: "Qui sera le dernier à lâcher son smartphone ?", cat: "futur" },
  { text: "Qui deviendra accro au développement personnel ?", cat: "futur" },
  { text: "Qui adoptera des enfants des quatre coins du monde ?", cat: "futur" },
  { text: "Qui prendra sa retraite le plus tôt ?", cat: "futur" },
  { text: "Qui finira par tout plaquer pour ouvrir une ferme ?", cat: "futur" },
  { text: "Qui se mariera avec quelqu'un rencontré ce soir-là ?", cat: "futur" },
  { text: "Qui sera encore exactement le même dans 30 ans ?", cat: "futur" },
  { text: "Qui deviendra le plus sage de nous tous ?", cat: "futur" },

  // ─── 👽 Absurde (fun) ───
  { text: "Qui rejoindrait une secte sans s'en rendre compte ?", cat: "absurde" },
  { text: "Qui aurait survécu à une autre époque ?", cat: "absurde" },
  { text: "Qui survivrait sur une île déserte ?", cat: "absurde" },
  { text: "Qui serait le meilleur dans Koh-Lanta ?", cat: "absurde" },
  { text: "Qui survivrait à une apocalypse zombie ?", cat: "absurde" },
  { text: "Qui serait l'imposteur dans Among Us ?", cat: "absurde" },
  { text: "Qui se ferait éliminer en premier dans Squid Game ?", cat: "absurde" },
  { text: "Qui mangerait un insecte pour 100€ ?", cat: "absurde" },
  { text: "Qui appellerait sa mère en premier en cas de problème ?", cat: "absurde" },
  { text: "Qui monterait une secte qui marche vraiment ?", cat: "absurde" },
  { text: "Qui ferait le meilleur cambrioleur ?", cat: "absurde" },
  { text: "Qui gagnerait une bagarre de bar ?", cat: "absurde" },
  { text: "Qui irait combattre un ours pour de l'argent ?", cat: "absurde" },
  { text: "Qui ferait le pire candidat de télé-réalité ?", cat: "absurde" },
  { text: "Qui paniquerait en premier dans un avion qui tremble ?", cat: "absurde" },
  { text: "Qui parlerait à un fantôme par pure curiosité ?", cat: "absurde" },
  { text: "Qui vendrait un rein pour partir en vacances ?", cat: "absurde" },
  { text: "Qui survivrait le plus longtemps dans un film d'horreur ?", cat: "absurde" },
  { text: "Qui serait le premier transformé en zombie ?", cat: "absurde" },
  { text: "Qui négocierait avec des extraterrestres ?", cat: "absurde" },
  { text: "Qui deviendrait le chef d'une bande de survivants ?", cat: "absurde" },
  { text: "Qui se ferait avoir par une arnaque par mail ?", cat: "absurde" },
  { text: "Qui se battrait avec une mouette pour une frite ?", cat: "absurde" },
  { text: "Qui parlerait à ses plantes pour qu'elles poussent ?", cat: "absurde" },
  { text: "Qui ramènerait un animal exotique illégal de vacances ?", cat: "absurde" },
  { text: "Qui deviendrait ami avec son ravisseur ?", cat: "absurde" },
  { text: "Qui gagnerait un concours de grimaces ?", cat: "absurde" },
  { text: "Qui tiendrait le plus longtemps sans rire ?", cat: "absurde" },
  { text: "Qui ferait le pire passager dans une voiture ?", cat: "absurde" },
  { text: "Qui déclencherait l'alarme incendie en faisant cuire des pâtes ?", cat: "absurde" },
  { text: "Qui survivrait à un escape game tout seul ?", cat: "absurde" },
  { text: "Qui tiendrait une conversation avec un mur en soirée ?", cat: "absurde" },
  { text: "Qui mangerait un plat clairement périmé pour ne pas gâcher ?", cat: "absurde" },

  // ─── 🧠 Philo (fun) ───
  { text: "Qui semble avoir tout compris à la vie ?", cat: "philo" },
  { text: "Qui est le plus en paix avec lui-même ?", cat: "philo" },
  { text: "Qui sera le plus regretté le jour où il partira ?", cat: "philo" },
  { text: "Qui pense à la mort un peu trop souvent ?", cat: "philo" },
  { text: "Qui vit comme si demain n'existait pas ?", cat: "philo" },
  { text: "Qui a le plus changé ces dernières années ?", cat: "philo" },
  { text: "Qui cache le mieux ses vraies émotions ?", cat: "philo" },
  { text: "Qui a le plus peur d'être vraiment connu ?", cat: "philo" },
  { text: "Qui fait semblant d'aller bien jusqu'au bout ?", cat: "philo" },
  { text: "Qui a le plus besoin de l'approbation des autres ?", cat: "philo" },
  { text: "Qui ment le plus à soi-même ?", cat: "philo" },
  { text: "Qui sait vraiment ce qu'il veut dans la vie ?", cat: "philo" },
  { text: "Qui a déjà tout remis en question du jour au lendemain ?", cat: "philo" },
  { text: "Qui se sent le plus libre ?", cat: "philo" },
  { text: "Qui a fait la paix avec son passé ?", cat: "philo" },
  { text: "Qui court après quelque chose qu'il n'atteindra jamais ?", cat: "philo" },
  { text: "Qui confond le bonheur avec la réussite ?", cat: "philo" },
  { text: "Qui a le plus de mal à vivre l'instant présent ?", cat: "philo" },
  { text: "Qui pardonnerait l'impardonnable ?", cat: "philo" },
  { text: "Qui changerait le moins s'il devenait immortel ?", cat: "philo" },
  { text: "Qui regrettera surtout ce qu'il n'a pas osé faire ?", cat: "philo" },
  { text: "Qui se connaît le mieux lui-même ?", cat: "philo" },
  { text: "Qui choisirait la vérité même si elle fait mal ?", cat: "philo" },
  { text: "Qui vit vraiment selon ses propres règles ?", cat: "philo" },
  { text: "Qui a le plus besoin de se sentir utile ?", cat: "philo" },
  { text: "Qui trouve un sens à tout ce qui lui arrive ?", cat: "philo" },
  { text: "Qui a le rapport le plus sain à la solitude ?", cat: "philo" },
  { text: "Qui s'inquiète le plus du regard des autres ?", cat: "philo" },
  { text: "Qui défendrait ses convictions quoi qu'il en coûte ?", cat: "philo" },
  { text: "Qui serait le plus serein face à la fin du monde ?", cat: "philo" },
  { text: "Qui a compris que le bonheur tient aux petites choses ?", cat: "philo" },
  { text: "Qui a le plus de mal à demander de l'aide ?", cat: "philo" },
  { text: "Qui deviendra quelqu'un de complètement différent dans 10 ans ?", cat: "philo" },

  // ─── 💔 Couple (spicy) ───
  { text: "Qui est le plus toxique en couple ?", cat: "couple" },
  { text: "Qui est le plus jaloux secrètement ?", cat: "couple" },
  { text: "Qui fait le moins d'efforts en relation ?", cat: "couple" },
  { text: "Qui a déjà ghosté quelqu'un sans pitié ?", cat: "couple" },
  { text: "Qui stalke le plus ses ex ?", cat: "couple" },
  { text: "Qui ment sur son nombre de partenaires ?", cat: "couple" },
  { text: "Qui sera le premier à divorcer ?", cat: "couple" },
  { text: "Qui finira seul avec 7 chats ?", cat: "couple" },
  { text: "Qui fuit dès que ça devient sérieux ?", cat: "couple" },
  { text: "Qui resterait en couple juste par confort ?", cat: "couple" },
  { text: "Qui retomberait dans les bras de son ex en une soirée ?", cat: "couple" },
  { text: "Qui attire toujours le même type de personnes ?", cat: "couple" },
  { text: "Qui envoie des messages qu'il regrette le lendemain ?", cat: "couple" },
  { text: "Qui tombe amoureux beaucoup trop vite ?", cat: "couple" },
  { text: "Qui a déjà été le plan B de quelqu'un ?", cat: "couple" },
  { text: "Qui drague le plus maladroitement ?", cat: "couple" },
  { text: "Qui fouille le téléphone de son partenaire ?", cat: "couple" },
  { text: "Qui ne tient pas deux semaines célibataire ?", cat: "couple" },
  { text: "Qui idéalise toujours la personne en face ?", cat: "couple" },
  { text: "Qui a déjà liké une vieille photo en stalkant ?", cat: "couple" },
  { text: "Qui enjolive son profil sur les applis de rencontre ?", cat: "couple" },
  { text: "Qui choisit exprès les relations compliquées ?", cat: "couple" },
  { text: "Qui dirait « je t'aime » beaucoup trop tôt ?", cat: "couple" },
  { text: "Qui a le plus de mal à tourner la page ?", cat: "couple" },
  { text: "Qui ferait une scène de jalousie en public ?", cat: "couple" },
  { text: "Qui pardonnerait une infidélité ?", cat: "couple" },
  { text: "Qui serait infidèle s'il était sûr de ne jamais se faire prendre ?", cat: "couple" },
  { text: "Qui parle de son ex un peu trop souvent ?", cat: "couple" },
  { text: "Qui change complètement de personnalité quand il est amoureux ?", cat: "couple" },
  { text: "Qui resterait ami avec tous ses ex ?", cat: "couple" },
  { text: "Qui craque toujours pour des gens inaccessibles ?", cat: "couple" },
  { text: "Qui confond le plus l'amour et l'attachement ?", cat: "couple" },

  // ─── 😬 Gênant (spicy) ───
  { text: "Qui oublie son portefeuille à chaque sortie ?", cat: "genant" },
  { text: "Qui a la galerie photo la plus suspecte ?", cat: "genant" },
  { text: "Qui a déjà envoyé un message à la mauvaise personne ?", cat: "genant" },
  { text: "Qui a la pire playlist secrète ?", cat: "genant" },
  { text: "Qui a déjà fait semblant de connaître une chanson ?", cat: "genant" },
  { text: "Qui a déjà fait semblant de ne pas voir quelqu'un dans la rue ?", cat: "genant" },
  { text: "Qui a l'historique de recherche le plus à cacher ?", cat: "genant" },
  { text: "Qui a déjà répondu « toi aussi » à « bon film » au cinéma ?", cat: "genant" },
  { text: "Qui parle beaucoup trop fort au téléphone en public ?", cat: "genant" },
  { text: "Qui a déjà appelé un prof « maman » ou « papa » ?", cat: "genant" },
  { text: "Qui a déjà vomi en soirée devant tout le monde ?", cat: "genant" },
  { text: "Qui se reprend en photo cinquante fois avant de poster ?", cat: "genant" },
  { text: "Qui envoie des messages vocaux de huit minutes ?", cat: "genant" },
  { text: "Qui like ses propres publications ?", cat: "genant" },
  { text: "Qui a déjà oublié un prénom en pleine présentation ?", cat: "genant" },
  { text: "Qui chante à tue-tête en voiture en croyant que personne ne voit ?", cat: "genant" },
  { text: "Qui a déjà fait tomber son téléphone sur son visage au lit ?", cat: "genant" },
  { text: "Qui raconte sa vie à des inconnus dans le train ?", cat: "genant" },
  { text: "Qui a déjà salué chaleureusement quelqu'un qu'il ne connaissait pas ?", cat: "genant" },
  { text: "Qui a déjà posté un truc gênant avant de vite le supprimer ?", cat: "genant" },
  { text: "Qui a la sonnerie de téléphone la plus gênante ?", cat: "genant" },
  { text: "Qui a déjà fait un lapsus très révélateur ?", cat: "genant" },
  { text: "Qui a déjà pleuré devant une publicité ?", cat: "genant" },
  { text: "Qui poste des stories que personne ne regarde ?", cat: "genant" },
  { text: "Qui a déjà prétendu avoir lu un livre qu'il n'a jamais ouvert ?", cat: "genant" },
  { text: "Qui se parle à lui-même devant le miroir ?", cat: "genant" },
  { text: "Qui trébuche en public et fait semblant que tout va bien ?", cat: "genant" },
  { text: "Qui a déjà dragué quelqu'un déjà en couple sans le savoir ?", cat: "genant" },
  { text: "Qui rit trop fort à ses propres blagues nulles ?", cat: "genant" },
  { text: "Qui garde des captures d'écran totalement inutiles ?", cat: "genant" },
  { text: "Qui met trois jours à répondre puis dit « désolé je viens de voir » ?", cat: "genant" },

  // ─── 🔥 Sans pitié (spicy) ───
  { text: "Qui ment le plus souvent ?", cat: "trash" },
  { text: "Qui ne pourrait pas garder un secret 24h ?", cat: "trash" },
  { text: "Qui te trahirait pour un million d'euros ?", cat: "trash" },
  { text: "Qui parle le plus dans le dos des autres ?", cat: "trash" },
  { text: "Qui est le plus égoïste sans s'en rendre compte ?", cat: "trash" },
  { text: "Qui changerait totalement s'il devenait riche ?", cat: "trash" },
  { text: "Qui pense être bien meilleur qu'il ne l'est ?", cat: "trash" },
  { text: "Qui a l'ego le plus fragile ?", cat: "trash" },
  { text: "Qui se prend beaucoup trop au sérieux ?", cat: "trash" },
  { text: "Qui regarde son téléphone pendant qu'on lui parle ?", cat: "trash" },
  { text: "Qui juge les autres en silence ?", cat: "trash" },
  { text: "Qui craquerait en premier sous la torture ?", cat: "trash" },
  { text: "Qui est le plus dramatique du groupe ?", cat: "trash" },
  { text: "Qui annule toujours à la dernière minute ?", cat: "trash" },
  { text: "Qui arrive systématiquement en retard ?", cat: "trash" },
  { text: "Qui sait le mieux mentir en gardant son sang-froid ?", cat: "trash" },
  { text: "Qui ferait fortune dans l'arnaque ?", cat: "trash" },
  { text: "Qui dénoncerait un ami qui a mal agi ?", cat: "trash" },
  { text: "Qui mentirait pour couvrir un proche coupable ?", cat: "trash" },
  { text: "Qui pardonne le moins ?", cat: "trash" },
  { text: "Qui est le plus manipulateur sans en avoir l'air ?", cat: "trash" },
  { text: "Qui trahirait ses valeurs pour de l'argent ?", cat: "trash" },
  { text: "Qui se croit secrètement irremplaçable ?", cat: "trash" },
  { text: "Qui n'a jamais vraiment assumé ses erreurs ?", cat: "trash" },
  { text: "Qui garde de la rancune le plus longtemps ?", cat: "trash" },
  { text: "Qui ferait passer son intérêt avant le groupe sans hésiter ?", cat: "trash" },
  { text: "Qui blesse les gens sans même s'en rendre compte ?", cat: "trash" },
  { text: "Qui a le plus de mal à s'excuser sincèrement ?", cat: "trash" },
  { text: "Qui sacrifierait une amitié pour réussir sa carrière ?", cat: "trash" },
  { text: "Qui ne verserait pas une larme à l'enterrement de la plupart des gens ici ?", cat: "trash" },
  { text: "Qui serait capable de couper les ponts avec sa famille sans regret ?", cat: "trash" },
  { text: "Qui couperait quelqu'un de sa vie sans la moindre explication ?", cat: "trash" },
  { text: "Qui choisit toujours son confort plutôt que ses amis ?", cat: "trash" },
  { text: "Qui balancerait un secret juste pour se rendre intéressant ?", cat: "trash" },
  { text: "Qui n'aiderait pas un ami si ça le dérangeait un peu ?", cat: "trash" },
  { text: "Qui est ami avec certaines personnes uniquement par intérêt ?", cat: "trash" },
  { text: "Qui ferait tout pour avoir le dernier mot ?", cat: "trash" },
  { text: "Qui se victimise pour fuir ses responsabilités ?", cat: "trash" },
  { text: "Qui oublierait ses amis dès qu'il trouve l'amour ?", cat: "trash" },
  { text: "Qui te planterait à la seconde où il a mieux à faire ?", cat: "trash" },
];
