import type { QuestionCategory } from "./constants.js";
import type { Question } from "./types.js";

const G = (n: number, text: string): Question => ({ id: `g${pad(n)}`, text, category: "gentil" });
const D = (n: number, text: string): Question => ({ id: `d${pad(n)}`, text, category: "drole" });
const H = (n: number, text: string): Question => ({ id: `h${pad(n)}`, text, category: "hot" });
const S = (n: number, text: string): Question => ({ id: `s${pad(n)}`, text, category: "secret" });

function pad(n: number): string {
  return n.toString().padStart(2, "0");
}

export const QUESTIONS: readonly Question[] = [
  // ── Gentil / Méchant ───────────────────────────────────────────
  G(1, "Qui est le plus gentil du groupe ?"),
  G(2, "Qui est le plus rancunier ?"),
  G(3, "Qui rendrait un portefeuille trouvé dans la rue ?"),
  G(4, "Qui pleurerait devant un film Pixar ?"),
  G(5, "Qui aiderait une vieille dame à traverser la rue sans hésiter ?"),
  G(6, "Qui ne laisse jamais de pourboire ?"),
  G(7, "Qui pardonne le plus facilement ?"),
  G(8, "Qui garde une dent contre quelqu'un pendant des années ?"),
  G(9, "Qui ferait passer ses amis avant lui-même ?"),
  G(10, "Qui est le plus égoïste sans s'en rendre compte ?"),
  G(11, "Qui envoie les messages d'anniversaire avec 3 jours de retard ?"),
  G(12, "Qui se souvient de la date d'anniversaire de tout le monde ?"),
  G(13, "Qui serait le plus susceptible de devenir bénévole le dimanche ?"),
  G(14, "Qui te défendrait dans une bagarre ?"),
  G(15, "Qui te dénoncerait pour sauver sa peau ?"),
  G(16, "Qui partage le mieux son dessert ?"),
  G(17, "Qui mange la dernière part sans demander ?"),
  G(18, "Qui est le plus diplomate dans une dispute ?"),
  G(19, "Qui est le plus passif-agressif ?"),
  G(20, "Qui ferait une scène au serveur d'un restaurant ?"),
  G(21, "Qui est le plus tolérant face aux différences ?"),
  G(22, "Qui juge les gens en cinq secondes ?"),
  G(23, "Qui prend ses proches pour acquis ?"),
  G(24, "Qui dit 'ça va' alors que ça ne va pas du tout ?"),
  G(25, "Qui poserait son manteau sur une flaque pour toi ?"),
  G(26, "Qui invente une excuse pour ne pas t'aider à déménager ?"),
  G(27, "Qui adopterait tous les chiens abandonnés du quartier ?"),
  G(28, "Qui te planterait un couteau dans le dos avec le sourire ?"),
  G(29, "Qui est le plus loyal en amitié ?"),
  G(30, "Qui ferait passer son couple avant tout le reste ?"),
  G(31, "Qui oublie systématiquement de répondre aux messages ?"),
  G(32, "Qui appelle toujours plutôt que d'écrire ?"),
  G(33, "Qui cache ses vrais sentiments derrière un sourire ?"),
  G(34, "Qui te donnerait son dernier billet sans hésiter ?"),
  G(35, "Qui te réclamerait 2 € que tu lui dois encore ?"),
  G(36, "Qui pète les plombs le plus vite dans les bouchons ?"),
  G(37, "Qui est le plus zen face aux galères ?"),
  G(38, "Qui balance ses collègues à la pause café ?"),
  G(39, "Qui défend les opprimés à un repas de famille ?"),
  G(40, "Qui adore voir quelqu'un se planter en public ?"),
  G(41, "Qui ramasse le verre cassé sans qu'on le demande ?"),
  G(42, "Qui pleure en triant ses vieilles affaires ?"),
  G(43, "Qui est dur en surface mais tendre dessous ?"),
  G(44, "Qui n'avouera jamais qu'il a tort ?"),
  G(45, "Qui s'excuse pour tout, même quand ce n'est pas sa faute ?"),
  G(46, "Qui préfère faire passer un message désagréable plutôt que parler en face ?"),
  G(47, "Qui est le plus capable de garder un secret ?"),
  G(48, "Qui balancerait un ragot juteux en moins d'une heure ?"),
  G(49, "Qui est le plus radin du groupe ?"),
  G(50, "Qui est généreux sans jamais s'en vanter ?"),

  // ── Drôle / Cringe ─────────────────────────────────────────────
  D(1, "Qui est le plus drôle du groupe ?"),
  D(2, "Qui rit le plus fort à ses propres blagues ?"),
  D(3, "Qui raconte des blagues qui ne font rire que lui ?"),
  D(4, "Qui oserait chanter en public à jeun ?"),
  D(5, "Qui ferait le plus gros malaise sur une piste de danse ?"),
  D(6, "Qui aurait honte de lui en revoyant la vidéo du karaoké ?"),
  D(7, "Qui devient incompréhensible après trois verres ?"),
  D(8, "Qui imite le mieux les accents ?"),
  D(9, "Qui a le rire le plus contagieux ?"),
  D(10, "Qui a le rire le plus gênant ?"),
  D(11, "Qui jouerait de la trompette dans le métro pour rigoler ?"),
  D(12, "Qui relèverait un défi de manger un piment entier ?"),
  D(13, "Qui ose le plus mal s'habiller ?"),
  D(14, "Qui glisserait sur une peau de banane en vrai ?"),
  D(15, "Qui parle à son chat en faisant des voix ?"),
  D(16, "Qui rejoue des scènes de séries quand il est seul ?"),
  D(17, "Qui danse devant le miroir le matin ?"),
  D(18, "Qui filme tous ses repas pour les stories ?"),
  D(19, "Qui répond avec des mèmes plutôt que des phrases ?"),
  D(20, "Qui envoie des messages vocaux de 3 minutes ?"),
  D(21, "Qui s'incruste dans toutes les photos de groupe ?"),
  D(22, "Qui prend les selfies les plus douteux ?"),
  D(23, "Qui posterait les statuts les plus cringe ?"),
  D(24, "Qui aurait son propre podcast totalement inutile ?"),
  D(25, "Qui fait pleurer de rire en racontant une histoire banale ?"),
  D(26, "Qui a la voix la plus reconnaissable ?"),
  D(27, "Qui ferait un commentateur sportif catastrophique ?"),
  D(28, "Qui rit nerveusement quand il est mal à l'aise ?"),
  D(29, "Qui balance des références que personne ne comprend ?"),
  D(30, "Qui relèverait un pari débile pour 10 € ?"),
  D(31, "Qui assume le moins ses goûts musicaux ?"),
  D(32, "Qui chante du Céline Dion sans aucun complexe ?"),
  D(33, "Qui a déjà appelé un prof 'maman' ou 'papa' ?"),
  D(34, "Qui s'est cogné dans une porte vitrée en pleine assurance ?"),
  D(35, "Qui s'est étalé devant tout le monde en faisant semblant que rien ?"),
  D(36, "Qui se parle à lui-même dans la rue ?"),
  D(37, "Qui a la phrase d'accroche la plus ratée ?"),
  D(38, "Qui aurait la pire bio Tinder ?"),
  D(39, "Qui prend les jeux de société beaucoup trop au sérieux ?"),
  D(40, "Qui ne sait jamais dire non à un karaoké ?"),
  D(41, "Qui a passé un mariage à danser tout seul ?"),
  D(42, "Qui a commencé une blague et a oublié la chute ?"),
  D(43, "Qui aurait déjà un humour de tonton à 22 ans ?"),
  D(44, "Qui imiterait le mieux son boss au bureau ?"),
  D(45, "Qui se croit drôle mais ne fait rire personne ?"),
  D(46, "Qui est le clown malgré lui ?"),
  D(47, "Qui aurait le plus de mal à rester sérieux à un enterrement ?"),
  D(48, "Qui éclate de rire au pire moment possible ?"),
  D(49, "Qui rejoue les scènes de film à voix haute ?"),
  D(50, "Qui finira viral pour une vidéo bien ratée ?"),

  // ── Hot / Froid ────────────────────────────────────────────────
  H(1, "Qui plaquerait tout pour partir au bout du monde ?"),
  H(2, "Qui resterait dans la même ville toute sa vie ?"),
  H(3, "Qui sauterait en parachute demain ?"),
  H(4, "Qui refuserait même un grand huit ?"),
  H(5, "Qui sortirait avec un inconnu dans les 24h ?"),
  H(6, "Qui planifie ses rendez-vous galants dans un Google Calendar ?"),
  H(7, "Qui prendrait un avion ce soir sans bagages ?"),
  H(8, "Qui répondrait au DM d'une célébrité ?"),
  H(9, "Qui draguerait son barista ?"),
  H(10, "Qui rougit dès qu'on lui fait un compliment ?"),
  H(11, "Qui aurait le plus d'ex à la même soirée ?"),
  H(12, "Qui n'arrive jamais à dire 'non' sur une app de rencontre ?"),
  H(13, "Qui a un coup de cœur tous les mois ?"),
  H(14, "Qui flirte sans même s'en rendre compte ?"),
  H(15, "Qui flirte trop en se croyant discret ?"),
  H(16, "Qui a déjà annulé un date pour rester sur le canapé ?"),
  H(17, "Qui partirait vivre en van demain matin ?"),
  H(18, "Qui prendrait un job au Japon en 48h ?"),
  H(19, "Qui se ferait tatouer sur un coup de tête ?"),
  H(20, "Qui n'a pas changé de coupe de cheveux depuis 10 ans ?"),
  H(21, "Qui irait à un cours de pole dance pour relever le défi ?"),
  H(22, "Qui irait en rave directement après le boulot ?"),
  H(23, "Qui irait au lit à 22h pile par principe ?"),
  H(24, "Qui prend un dessert différent à chaque resto ?"),
  H(25, "Qui commande toujours exactement la même chose ?"),
  H(26, "Qui irait nager à minuit dans une piscine inconnue ?"),
  H(27, "Qui ferait un strip-tease pour gagner 100 € ?"),
  H(28, "Qui a peur d'être perçu comme ennuyeux ?"),
  H(29, "Qui est franchement ennuyeux mais ne le sait pas ?"),
  H(30, "Qui a la vie de couple la plus enviable ?"),
  H(31, "Qui aurait le plus de mal à rester fidèle ?"),
  H(32, "Qui retournerait avec son ex en deux clics ?"),
  H(33, "Qui croit dur comme fer au coup de foudre ?"),
  H(34, "Qui pense que l'amour est complètement dépassé ?"),
  H(35, "Qui ose le plus au lit (sans répondre à voix haute) ?"),
  H(36, "Qui ferait une thérapie de couple sans hésiter ?"),
  H(37, "Qui se marierait à Las Vegas dès ce week-end ?"),
  H(38, "Qui ne se mariera jamais par principe ?"),
  H(39, "Qui fait toujours le premier pas ?"),
  H(40, "Qui attend toujours que l'autre se déclare ?"),
  H(41, "Qui sortirait en boîte un mardi soir ?"),
  H(42, "Qui tenterait le saut à l'élastique sans réfléchir ?"),
  H(43, "Qui ne tenterait jamais une expérience culinaire bizarre ?"),
  H(44, "Qui mangerait des insectes pour 50 € ?"),
  H(45, "Qui se trouve le plus beau au réveil ?"),
  H(46, "Qui prend deux heures à se préparer avant de sortir ?"),
  H(47, "Qui est prêt en cinq minutes chrono ?"),
  H(48, "Qui draguerait quelqu'un déjà pris ?"),
  H(49, "Qui retournerait sa veste pour gagner un canapé gratuit ?"),
  H(50, "Qui giflerait un inconnu pour gagner 1000 € ?"),

  // ── Secret / Public ────────────────────────────────────────────
  S(1, "Qui cache le plus de choses au groupe ?"),
  S(2, "Qui est un livre ouvert sur sa vie ?"),
  S(3, "Qui a la double vie la plus convaincante ?"),
  S(4, "Qui poste sa vie en stories toutes les heures ?"),
  S(5, "Qui a forcément un compte Insta secret quelque part ?"),
  S(6, "Qui googlerait son propre prénom le plus souvent ?"),
  S(7, "Qui dort avec son téléphone sous l'oreiller ?"),
  S(8, "Qui efface son historique de recherche tous les soirs ?"),
  S(9, "Qui répond exprès tard aux messages pour faire mystère ?"),
  S(10, "Qui tient encore un journal intime caché quelque part ?"),
  S(11, "Qui a le plus de squelettes dans le placard ?"),
  S(12, "Qui invente sa vie sur les apps de rencontre ?"),
  S(13, "Qui ment sur son âge ?"),
  S(14, "Qui ment sur sa taille ?"),
  S(15, "Qui ment sur son salaire ?"),
  S(16, "Qui ment même quand ça n'a aucun intérêt ?"),
  S(17, "Qui sait raconter un mensonge avec un aplomb diabolique ?"),
  S(18, "Qui rougit au moindre petit mensonge ?"),
  S(19, "Qui reste le plus mystérieux en première rencontre ?"),
  S(20, "Qui balance toute sa vie dès la première rencontre ?"),
  S(21, "Qui parle de son ex le plus souvent ?"),
  S(22, "Qui n'évoquerait jamais son ex devant nous ?"),
  S(23, "Qui a le passé le plus rock'n'roll ?"),
  S(24, "Qui aurait le plus honte en relisant son journal de 14 ans ?"),
  S(25, "Qui cache un secret qu'aucun de nous ne soupçonne ?"),
  S(26, "Qui est le plus imprévisible du groupe ?"),
  S(27, "Qui est tellement prévisible qu'on connaît la suite à l'avance ?"),
  S(28, "Qui surveille en silence les ex sur Instagram ?"),
  S(29, "Qui stalke chaque nouveau collègue dès le premier jour ?"),
  S(30, "Qui a déjà créé un faux profil ?"),
  S(31, "Qui se ment à lui-même le plus ?"),
  S(32, "Qui n'assume pas une partie de ses goûts ?"),
  S(33, "Qui mentirait à son médecin sans hésiter ?"),
  S(34, "Qui ment sur la note de son dernier examen ?"),
  S(35, "Qui exagère ses voyages quand il en parle ?"),
  S(36, "Qui a déjà fouillé le téléphone d'un proche ?"),
  S(37, "Qui a un mot de passe ridiculement facile à deviner ?"),
  S(38, "Qui change tous ses mots de passe tous les mois ?"),
  S(39, "Qui préfère parler à un thérapeute plutôt qu'à ses amis ?"),
  S(40, "Qui appellerait son ex en cas de coup dur ?"),
  S(41, "Qui balance des piques et fait ensuite l'innocent ?"),
  S(42, "Qui pleure en cachette ?"),
  S(43, "Qui n'a jamais pleuré devant nous mais le fait souvent seul ?"),
  S(44, "Qui n'a absolument aucun filtre ?"),
  S(45, "Qui filtre 90 % de ce qu'il pense ?"),
  S(46, "Qui ferait un excellent thriller de sa propre vie ?"),
  S(47, "Qui regarde son partenaire dormir pour se rassurer ?"),
  S(48, "Qui consulte son téléphone toutes les deux minutes ?"),
  S(49, "Qui a un compte d'épargne secret ?"),
  S(50, "Qui a déjà inventé une excuse bidon pour annuler un plan ?"),
];

export function questionsByCategory(): Record<QuestionCategory, Question[]> {
  return {
    gentil: QUESTIONS.filter((q) => q.category === "gentil"),
    drole: QUESTIONS.filter((q) => q.category === "drole"),
    hot: QUESTIONS.filter((q) => q.category === "hot"),
    secret: QUESTIONS.filter((q) => q.category === "secret"),
  };
}
